#!/usr/bin/env bash
KUBECONFIG="$1"
declare_variables() {
    KUBECONFIGS=($(ls ~/.kube/*-eks | sort))
    ALIAS="kprofile"
    r="\033[0;31m" # red
    y="\033[1;33m" # yellow
    x="\033[0m" # reset
}

kprofile_help() {
    echo "Usage: kprofile <kubeconfig-location>"
    echo
    echo "Configured profiles  : ${KUBECONFIGS[@]}"
}

set_profile() {
if [ -z "$KUBECONFIG" ];  then
    kprofile_help
elif [[ ! " ${KUBECONFIGS[@]} " =~ " ${KUBECONFIG} " ]]; then
    echo -e "Error: profile ${r}${KUBECONFIG}${x} not found"
    kprofile_help
else
    export KUBECONFIG=${KUBECONFIG}
fi
}

main() {
    declare_variables
    set_profile
}

main
